import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Message List App",
  description: "Generated by create next app",
  // Otra forma de insertar un icon:
  // icons: {
  //   icon: {
  //     url: "/favicon.ico",
  //     type: "image/x-icon",
  //   },
  //   shortcut: { url: "/favicon.ico", type: "image/x-icon" },
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="./favicon.ico" type="image/x-icon" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
